--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/BuilderTools
branches:
- '2.0.0'
projects:
  BuilderTools:
    path: ''
    icon: 'icon.png'
    lint:
      phpstan: false
...
