--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/BuilderTools
branches:
- main
- api/pm3
- feature/tiles
- 1.3.1
projects:
  BuilderTools:
    path: ''
    icon: 'icon.png'
...
