name: BuilderTools
api: [4.0.0]
author: CzechPMDevs
authors: [VixikHD]
version: 1.3.1
main: czechpmdevs\buildertools\BuilderTools
website: https://github.com/CzechPMDevs/BuilderTools

extensions:
  Core: '>=8.0'

permissions:
  buildertools.command:
    default: op
    description: Permissions for all BuilderTools commands
  buildertools.command.biome:
    description: Permissions for //blockinfo
    default: op
  buildertools.command.blockinfo:
    description: Permissions for //blockinfo
    default: op
  buildertools.command.center:
    description: Permissions for //center
    default: op
  buildertools.command.clearinventory:
    description: Permissions for //clearinventory
    default: op
  buildertools.command.copy:
    description: Permissions for //copy
    default: op
  buildertools.command.cube:
    description: Permissions for //cube
    default: op
  buildertools.command.cut:
    description: Permissions for //cut
    default: op
  buildertools.command.cylinder:
    description: Permission for //cylinder
    default: op
  buildertools.command.decoration:
    description: Permission for //decoration
    default: op
  buildertools.command.draw:
    description: Permission for //draw
    default: op
  buildertools.command.fill:
    descripion: Permissions for //fill
    default: op
  buildertools.command.pos1:
    description: Permissions for //pos1
    default: op
  buildertools.command.fix:
    descripion: Permissions for //fix
    default: op
  buildertools.command.flip:
    descripion: Permissions for //flip
    default: op
  buildertools.command.help:
    description: Permissions for //commands
    default: op
  buildertools.command.hcube:
    description: Permission for //hcube
    default: op
  buildertools.command.hcylinder:
    description: Permission for //hcylinder
    default: op
  buildertools.command.hpyramid:
    description: Permission for //hpyramid
    default: op
  buildertools.command.hsphere:
    descripton: Permissions for //hsphere
    default: op
  buildertools.command.id:
    description: Permissions for //id
    default: op
  buildertools.command.island:
    description: Permissions for //island
    default: op
  buildertools.command.merge:
    description: Permissions for //merge
    default: op
  buildertools.command.move:
    description: Permission for //move
    default: op
  buildertools.command.naturalize:
    description: Permissions for //naturalize
    default: op
  buildertools.command.outline:
    description: Permission for //outline
    default: op
  buildertools.command.paste:
    description: Permissions for //paste
    default: op
  buildertools.command.pyramid:
    description: Permission for //pyramid
    default: op
  buildertools.command.redo:
    description: Permission for //redo
    default: op
  buildertools.command.replace:
    description: Permission for //replace
    default: op
  buildertools.command.rotate:
    description: Permission for //rotate
    default: op
  buildertools.command.schematic:
    description: Permission for //schematics
    default: op
  buildertools.command.pos2:
    description: Permissions for //pos2
    default: op
  buildertools.command.sphere:
    description: Permissions for //sphere
    default: op
  buildertools.command.stack:
    description: Permission for //stack
    default: op
  buildertools.command.tree:
    description: Permission for //tree
    default: op
  buildertools.command.undo:
    description: Permission for //undo
    default: op
  buildertools.command.walls:
    description: Permission for //walls
    default: op
  buildertools.command.wand:
    description: Permissions for //wand
    default: op
